import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader";
import { useLoader } from "@react-three/fiber";
import Thin from "@/models/Thin";
import { OrbitControls } from "@react-three/drei";
import Fat from "@/models/Fat";
import { Suspense } from "react";
import Fatpants from "@/models/clothes/pants/fat/Fatpants";
import Thinpants from "@/models/clothes/pants/thin/ThinPants";
import FatTshirt from "@/models/clothes/tshirt/fat/FatTshirt";
import ThinTshirt from "@/models/clothes/tshirt/thin/ThinTshirt";

export default function Home() {
  const [avatar, setAvatar] = useState(false)
  const [viewFatTshirt, setViewFatTshirt] = useState(false);
  const [viewFatPants, setViewFatPants] = useState(false);
  const [viewThinTshirt, setViewThinTshirt] = useState(false);
  const [viewThinPants, setViewThinPants] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={() => setAvatar(!avatar)}>Avatar</button>
        <br />
        <button onClick={() => setViewFatTshirt(!viewFatTshirt)}>
          T-shirt(Fat)
        </button>
        <button onClick={() => setViewFatPants(!viewFatPants)}>
          Pants(Fat)
        </button>
        <br />
        <button onClick={() => setViewThinTshirt(!viewThinTshirt)}>
          T-shirt(Thin)
        </button>
        <button onClick={() => setViewThinPants(!viewThinPants)}>
          Pants(Thin)
        </button>
        <Canvas camera={{ position: [0, 0, 2] }}>
          {/* lights */}
          <ambientLight intensity={0.1} />
          <directionalLight position={[2, 2, 2]} intensity={0.1} />
          <directionalLight position={[-2, 2, -2]} intensity={0.1} />
          {/* controls */}
          <OrbitControls />


          {/* Clothes */}
          <Suspense fallback={null}>
          {/* Avatar */}
            {avatar && <Thin position={[0, -1, 0]} />}
            {!avatar && <Fat position={[0, -1, 0]} />}
            {viewFatTshirt && <FatTshirt position={[0, -1.13, 0.0005]} scale={0.0011} />}
            {viewFatPants && <Fatpants position={[0, -1, 0]} scale={0.001} />}
            {viewThinTshirt && <ThinTshirt position={[0, -1, 0]} scale={0.001} />}
            {viewThinPants && <Thinpants position={[0, -1, 0]} scale={0.001} />}
          </Suspense>
        </Canvas>
      </main>
    </>
  );
}
